<?

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

function logg($object, $label=null) {
  print($label . ":");
  echo "<br />";
  dump($object);
}

function puts($object, $label=null) {
  print($label . ":");
  echo "<br />";
  dump($object);
}


function ish_drupal_module_entity_type_build(array &$entity_types) {
  $entity_types['node']->setFormClass('for_youtube', 'Drupal\node\NodeForm');
  // $entity_types['node']->setFormClass('for_youtube', 'ForYoutube');
}

/**
 * Implements hook_theme().
 *
 * See: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_theme/8.2.x
 *
 * If you change this method, clear theme registry and routing
 * table 'drush cc theme-registry' and 'drush cc router'.
**/
function ish_drupal_module_theme($existing, $type, $theme, $path) {

  return [
    'error_404' => [
      'render element' => 'children',
      'template' => 'error_404',
      'path' => $path . '/templates',
      'variables' => [],
    ],

    'ish_users_dashboard' => [
      'template' => 'dashboard',
      'path' => $path . '/templates/users',
      'variables' => [
        'for_youtube_form' => NULL,
      ],
    ],
    'ish_users_edit' => [
      'template' => 'edit',
      'path' => $path . '/templates/users',
      'variables' => [
      ],
    ],
    'ish_locations_show' => [
      // 'render element' => 'requirements',
      'template' => 'show',
      'path' => $path . '/templates/locations',
      'variables' => [
        'location' => NULL,
        // 'request' => NULL,
      ],
    ],


    'menu_user_authenticated' => [
      'path' => $path . '/templates',
      // 'render element' => 'children',
      'template' => 'menu_user_authenticated',
      'variables' => [
        'testvar' => NULL,
      ],
    ],

    'my_feed' => [
      'path' => $path . '/templates',
      'render element' => 'elements', // works?!
      'template' => 'my_feed',
      'variables' => [
        'test_var_1' => null,
      ],
    ],

    'tags_show' => [
      'render element' => 'children',
      'template' => 'show',
      'path' => $path . '/templates/tags',
      'variables' => [
        'tag' => null,
        'features' => [],
        'newsitems' => [],
      ],
    ],

    'videos_show2' => [
      'template' => 'show2',
      'path' => $path. '/templates/videos',
      'variables' => [
        'content' => NULL,
      ],
    ],

    'youtube_check_channels' => [
      'render element' => 'children',
      'template' => 'check_channels',
      'path' => $path . '/templates/youtube',
      'variables' => [
      ],
    ],

  ];

}


function ish_drupal_module_entity_form_display_alter(Drupal\Core\Entity\Entity\EntityFormDisplay &$form_display, array $context) {
  if (in_array('authenticated', \Drupal::currentUser()->getRoles()) &&
      $context['entity_type'] === 'node' &&
      $context['bundle'] === 'aphorism') {
    $storage = \Drupal::entityTypeManager()->getStorage('entity_form_display');
    $differentDisplay = $storage->load("{$context['entity_type']}.{$context['bundle']}.contribute"); // 'my_form_display' was created via /admin/structure/display-modes/form
    if ($differentDisplay) {
      $form_display = $differentDisplay;
    }
  }
}


/* Redirect user on login.
 * From: https://drupal.stackexchange.com/questions/195170/redirect-after-user-login
 * Works!
**/
function ish_drupal_module_form_user_login_form_alter(&$form, $form_state) {
  $form['#submit'][] = 'ish_drupal_module_user_login_submit';
}
function ish_drupal_module_user_login_submit(&$form, $form_state) {
  $url = Url::fromRoute('ish_drupal_module.users_dashboard');
  // Check if a destination was set, probably on an exception controller.
  // @see \Drupal\user\Form\UserLoginForm::submitForm()
  $request = \Drupal::service('request_stack')->getCurrentRequest();
  if (!$request->request->has('destination')) {
    $form_state->setRedirectUrl($url);
  }
  else {
    $request->query->set('destination', $request->request->get('destination'));
  }
}

/**
 * For bjjcollective_com: related nodes for v2 type of video.
**/
function ish_drupal_module_node_view(&$build) {
  if ('v2' == $build['uid']['#bundle'] && 'full' == $build['#view_mode']) {
    $this_node = Node::load($build['#node']->nid[0]->value);
    $tags = [];
    foreach( $this_node->field_tags2 as $k => $v ) {
      array_push( $tags, $v->target_id );
    }
    $nids = \Drupal::entityQuery('node')->condition('field_tags2', $tags, 'in')->execute();
    if (($key = array_search($build['#node']->nid[0]->value, $nids)) !== false) { ## https://stackoverflow.com/questions/7225070/php-array-delete-by-value-not-key
      unset($nids[$key]);
    }
    $relatedNodes = \Drupal\node\Entity\Node::loadMultiple($nids);
    $relatedNodesView = \Drupal::entityTypeManager()
      ->getViewBuilder('node')
      ->viewMultiple($relatedNodes, 'card');
    $build['relatedNodes'] = $relatedNodesView;
  }
}
