<?
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;


// function ish_drupal_module_form_user_register_form_alter(&$form, $form_state, $form_id) {
//   // $form['account']['name']['#title'] = t('First and last name');
//   // $form['account']['name']['#description'] = t("Rewrite this about spaces, periods (.), hyphens (-) and apostrophes (').");
//
//   // $markup = '<div id="my-custom-markup"><h1>Here is my markup</h1></div>';
//   // $form['field_mycustommarkup'] = [
//   //     '#type' => 'markup',
//   //     '#markup' => $markup,
//   //     '#weight' => 1,
//   // ];
//
//   // $markup = '<div id="my-custom-markup"><h1>New 222 Recaptcha</h1></div>';
//   // $form['field_mycustommarkup'] = [
//   //     '#type' => 'markup',
//   //     '#markup' => $markup,
//   //     '#weight' => 10,
//   // ];
//
//   // $form['#submit'][] = 'ish_drupal_module_2_submit';
// }

// function ish_drupal_module_2_submit($form_id, $form_values) {
//   drupal_set_message(t('Submit Function Executed!'));
//   var_dump("And this, the form has been submitted.");
//   var_dump( $form_id );
//   var_dump( $form_values );
//   exit(0);
// }

function ish_drupal_module_entity_type_build(array &$entity_types) {
  $entity_types['node']->setFormClass('for_youtube', 'Drupal\node\NodeForm');
  // $entity_types['node']->setFormClass('for_youtube', 'ForYoutube');
}

/**
 * Implements hook_theme().
 *
 * See: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_theme/8.2.x
 *
 * If you change this method, clear theme registry and routing
 * table 'drush cc theme-registry' and 'drush cc router'.
**/
function ish_drupal_module_theme($existing, $type, $theme, $path) {

  return [
    'error_404' => [
      'render element' => 'children',
      'template' => 'error_404',
      'path' => $path . '/templates',
      'variables' => [],
    ],

    'ish_users_dashboard' => [
      'template' => 'dashboard',
      'path' => $path . '/templates/users',
      'variables' => [
        'for_youtube_form' => NULL,
      ],
    ],
    'ish_users_edit' => [
      'template' => 'edit',
      'path' => $path . '/templates/users',
      'variables' => [
      ],
    ],
    'ish_locations_show' => [
      // 'render element' => 'requirements',
      'template' => 'show',
      'path' => $path . '/templates/locations',
      'variables' => [
        'location' => NULL,
        // 'request' => NULL,
      ],
    ],

    'menu_user_authenticated' => [
      'path' => $path . '/templates',
      // 'render element' => 'children',
      'template' => 'menu_user_authenticated',
      'variables' => [
        'testvar' => NULL,
      ],
    ],

    'my_feed' => [
      'path' => $path . '/templates',
      'render element' => 'elements', // works?!
      'template' => 'my_feed',
      'variables' => [
        'test_var_1' => null,
      ],
    ],

    'tags_show' => [
      'render element' => 'children',
      'template' => 'show',
      'path' => $path . '/templates/tags',
      'variables' => [
        'tag' => null,
        'features' => [],
        'newsitems' => [],
      ],
    ],
  ];

}


function ish_drupal_module_entity_form_display_alter(Drupal\Core\Entity\Entity\EntityFormDisplay &$form_display, array $context) {
  if (in_array('authenticated', \Drupal::currentUser()->getRoles()) &&
      $context['entity_type'] === 'node' &&
      $context['bundle'] === 'aphorism') {
    $storage = \Drupal::entityTypeManager()->getStorage('entity_form_display');
    $differentDisplay = $storage->load("{$context['entity_type']}.{$context['bundle']}.contribute"); // 'my_form_display' was created via /admin/structure/display-modes/form
    if ($differentDisplay) {
      $form_display = $differentDisplay;
    }
  }
}



/* Redirect user on login.
 * From: https://drupal.stackexchange.com/questions/195170/redirect-after-user-login
 * Works!
**/
function ish_drupal_module_form_user_login_form_alter(&$form, $form_state) {
  $form['#submit'][] = 'ish_drupal_module_user_login_submit';
}
function ish_drupal_module_user_login_submit(&$form, $form_state) {
  $url = Url::fromRoute('ish_drupal_module.users_dashboard');
  // Check if a destination was set, probably on an exception controller.
  // @see \Drupal\user\Form\UserLoginForm::submitForm()
  $request = \Drupal::service('request_stack')->getCurrentRequest();
  if (!$request->request->has('destination')) {
    $form_state->setRedirectUrl($url);
  }
  else {
    $request->query->set('destination', $request->request->get('destination'));
  }
}
